### PR TITLE
Fixed: Hidden item-divider when Channels are not found and Moved channel options at last of the list(#228)

### LINKED ISSUE #228: Hide item-divider when channels are not found
## Current behavior
 
The item divider for channels is always displayed on UI even when channels are not present in facility resulting in confusion.

 ## Expected behavior
 
If the channels are not present on facility the item-divider should not be displayed.

Handle the below case as well:
https://github.com/hotwax/threshold-management/issues/228#issuecomment-1878176719

 ## Steps to reproduce the issue
 
- Login to a instance on which facility channels are not present
- Go to Create Rule page
- Enter threshold and then click on save threshold button
- Verify that the channels divider is always displayed even when facility channels are not available.

 ## Can you handle fixing this bug by yourself?

 - [x] YES
 - [ ] NO

 ## Environment details
 
 - Browser: 
 - OS: 
 - Code Version: 

 ## Additional information
 
image

### PR DESCRIPTION
**Pull request by shanmukhdutt**
### Related Issues
 

 Closes #228 

 ### Short Description and Why It's Useful
 

 ### Screenshots of Visual Changes before/after (If There Are Any)
 
 Before 
Screenshot from 2024-01-08 14-13-09

After
 Screenshot from 2024-01-08 12-40-17

 **IMPORTANT NOTICE** - Remember to add changelog entry

 ### Contribution and Currently Important Rules Acceptance
 

 - [ ] I read and followed [contribution rules](https://github.com/hotwax/threshold-management#contribution-guideline)

### CODE REVIEW

File: src/views/ScheduleThreshold.vue [hunk 1]
```diff
@@ -50,6 +43,13 @@
                 </ion-content>
               </ion-modal>
             </ion-item>
+            <ion-item-divider v-if="channels.length > 0" color="light">
```
Comment (ymaheshwari1) [inline src/views/ScheduleThreshold.vue:46]:
```suggestion
            <ion-item-divider v-if="channels.length" color="light">
```

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]
Please add a screenshot that how the page looks before this change.

**Review by ymaheshwari1 — APPROVED** [review]
